import { inter } from '@/app/ui/fonts';
import '@/app/ui/globals.css';
import type { Metadata } from 'next';
import { ThemeProvider } from './lib/theme-provider';

export const metadata: Metadata = {
  title: 'Food ',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
